config {
 database: dataform.projectConfig.defaultDatabase,
 schema: "billing_" + dataform.projectConfig.vars.ENV,
 name: "model_gemini",
 description: "",
 tags: [
   "stage:source",
   "lifecycle:deactive"
 ]
}


CREATE OR REPLACE MODEL `${dataform.projectConfig.defaultDatabase}.${"billing_" + dataform.projectConfig.vars.ENV}.model_gemini`
REMOTE WITH CONNECTION `EU.billing_gemini_connection`
OPTIONS(endpoint = 'gemini-pro')
